version: '3'
services:
  ma:
    container_name: ma
    build: .
    image: ma
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0"
    ports:
      - 3010:3000
    volumes:
      - .:/app:rw
      - ma-data-tmp:/app/tmp:cached
      - ./public/system:/app/public/system:cached
    tty: true
    stdin_open: true
    env_file: .env
  ma-nginx:
    container_name: ma-nginx
    image: nginx:latest
    ports:
      - 3000:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ma
volumes:
  ma-data-tmp:
    driver: local
